---
language: go
go:
- 1.8
sudo: required
services:
- docker
script:
- go test
- ./docker/test.sh
- docker login -u "$DOCKER_USERNAME" -p "$DOCKER_PASSWORD"
- docker push "$DOCKER_USERNAME"/certmaster-server
- docker push "$DOCKER_USERNAME"/certmaster-client
