FROM golang:1.8 as builder

WORKDIR /go/src/github.com/auvideus/certmaster

COPY . .

RUN go get -d -v ./cmd/certmaster-server \
    && go get -d -v ./cmd/certmaster-authhook \
    && go get -d -v ./cmd/certmaster-cleanuphook \
    && CGO_ENABLED=0 GOOS=linux go install -v ./cmd/certmaster-server \
    && CGO_ENABLED=0 GOOS=linux go install -v ./cmd/certmaster-authhook \
    && CGO_ENABLED=0 GOOS=linux go install -v ./cmd/certmaster-cleanuphook

FROM golang:1.8-alpine3.5 as runner

RUN apk add --no-cache certbot

COPY --from=builder /go/bin/certmaster-* /bin/

WORKDIR /opt/certmaster

ADD hooks/pre.sh .
ADD hooks/post.sh .

VOLUME /etc/letsencrypt

CMD ["certmaster-server"]
