FROM golang:1.8 as builder

WORKDIR /go/src/github.com/auvideus/certmaster

COPY . .

RUN go get -d -v ./cmd/certmaster-client \
    && CGO_ENABLED=0 GOOS=linux go install -v ./cmd/certmaster-client

FROM golang:1.9-alpine3.7 as runner

RUN apk add --update --no-cache openssh openssh-client rsync

COPY --from=builder /go/bin/certmaster-* /bin/

ADD docker/config /root/.ssh/

RUN chmod 600 /root/.ssh/config

WORKDIR /etc
WORKDIR /etc/certmaster

VOLUME /etc/letsencrypt

CMD ["certmaster-client"]
