FROM golang:1.8 as builder

WORKDIR /go/src/github.com/auvideus/certmaster

COPY . .

RUN go get -d -v github.com/auvideus/certmaster/cmd/certmaster-server \
    && go get -d -v github.com/auvideus/certmaster/cmd/certmaster-authhook \
    && go get -d -v github.com/auvideus/certmaster/cmd/certmaster-cleanuphook \
    && CGO_ENABLED=0 GOOS=linux go install -v ./cmd/certmaster-server \
    && CGO_ENABLED=0 GOOS=linux go install -v ./cmd/certmaster-authhook \
    && CGO_ENABLED=0 GOOS=linux go install -v ./cmd/certmaster-cleanuphook

FROM golang:1.9-alpine3.7 as runner

RUN apk add --update --no-cache certbot

COPY --from=builder /go/bin/certmaster-* /bin/

WORKDIR /etc/certmaster

ADD hooks/pre.sh .
ADD hooks/post.sh .

VOLUME /etc/letsencrypt

CMD ["certmaster-server"]
