FROM golang:1.8 as builder

WORKDIR /go/src/github.com/auvideus/certmaster

COPY . .

RUN go get -d -v ./cmd/certmaster-client \
    && CGO_ENABLED=0 GOOS=linux go install -v ./cmd/certmaster-client

FROM golang:1.9-alpine3.7 as runner

RUN apk add --update --no-cache rsync openssh openssh-client

COPY --from=builder /go/bin/certmaster-* /bin/

WORKDIR /etc/certmaster

VOLUME /etc/letsencrypt

CMD ["certmaster-client"]
